In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import folium
import matplotlib.pyplot as plt

In [15]:
df = pd.read_excel('데이터관련/houseprice2021.xlsx')
df.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,경기도 가평군 가평읍 달전리,281,281,0,세대넥스빌,71.430,202104,13,12700,3,1996,달전로 59
1,경기도 가평군 가평읍 달전리,281,281,0,세대넥스빌,78.840,202106,15,11900,5,1996,달전로 59
2,경기도 가평군 가평읍 달전리,285-1,285,1,신초,71.735,202007,7,11400,2,1993,달전로 64
3,경기도 가평군 가평읍 달전리,285-1,285,1,신초,84.875,202008,10,8300,11,1993,달전로 64
4,경기도 가평군 가평읍 대곡리,230-18,230,18,삼성웰타운아파트,82.739,202007,7,25000,5,2019,굴다리길 7-1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96676 entries, 0 to 96675
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       96676 non-null  object
 1   번지        96676 non-null  object
 2   본번        96676 non-null  object
 3   부번        96676 non-null  int64
 4   단지명       96676 non-null  object
 5   전용면적(㎡)   96676 non-null  float64
 6   계약년월      96676 non-null  int64
 7   계약일       96676 non-null  int64
 8   거래금액(만원)  96676 non-null  int64
 9   층         96676 non-null  int64
 10  건축년도      96676 non-null  int64
 11  도로명       96676 non-null  object
dtypes: float64(1), int64(6), object(5)
memory usage: 8.9+ MB

In [17]:
df7085 = df['전용면적(㎡)'] >= 70

df = df[df7085]

df

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,경기도 가평군 가평읍 달전리,281,281,0,세대넥스빌,71.4300,202104,13,12700,3,1996,달전로 59
1,경기도 가평군 가평읍 달전리,281,281,0,세대넥스빌,78.8400,202106,15,11900,5,1996,달전로 59
2,경기도 가평군 가평읍 달전리,285-1,285,1,신초,71.7350,202007,7,11400,2,1993,달전로 64
3,경기도 가평군 가평읍 달전리,285-1,285,1,신초,84.8750,202008,10,8300,11,1993,달전로 64
4,경기도 가평군 가평읍 대곡리,230-18,230,18,삼성웰타운아파트,82.7390,202007,7,25000,5,2019,굴다리길 7-1
...,...,...,...,...,...,...,...,...,...,...,...,...
96671,경기도 화성시 향남읍 행정리,475,475,0,화성향남시범복사꽃마을상록하늘채아파,84.8478,202104,8,41800,2,2009,행정동로 83
96672,경기도 화성시 향남읍 행정리,475,475,0,화성향남시범복사꽃마을상록하늘채아파,84.8478,202104,28,40000,10,2009,행정동로 83
96673,경기도 화성시 향남읍 행정리,475,475,0,화성향남시범복사꽃마을상록하늘채아파,84.8478,202105,11,38000,7,2009,행정동로 83
96674,경기도 화성시 향남읍 행정리,475,475,0,화성향남시범복사꽃마을상록하늘채아파,84.8478,202106,14,41400,10,2009,행정동로 83
96675,경기도 화성시 향남읍 행정리,475,475,0,화성향남시범복사꽃마을상록하늘채아파,84.8478,202106,19,42000,13,2009,행정동로 83

In [18]:
df_group = df.groupby(['시군구'], as_index=False).mean()

In [19]:
df_group

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
0,경기도 가평군 가평읍 달전리,0.500000,76.720000,202056.250000,11.250000,11075.000000,5.250000,1994.500000
1,경기도 가평군 가평읍 대곡리,4.250000,84.202857,202059.678571,16.928571,24637.500000,7.714286,2008.642857
2,경기도 가평군 가평읍 읍내리,2.035714,83.522804,202067.142857,16.642857,17846.428571,6.464286,2003.214286
3,경기도 가평군 설악면 선촌리,0.000000,84.542222,202035.944444,16.666667,26830.555556,8.722222,2014.000000
4,경기도 가평군 청평면 청평리,6.182482,83.086917,202060.919708,15.204380,19215.051095,7.182482,2007.248175
...,...,...,...,...,...,...,...,...
546,경기도 화성시 청계동,0.000000,83.418477,202042.537112,16.430499,83308.272605,12.770580,2015.317139
547,경기도 화성시 향남읍 발안리,0.000000,80.338968,202047.731183,14.580645,23192.473118,9.881720,2006.000000
548,경기도 화성시 향남읍 장짐리,2.098592,83.685451,202067.690141,15.633803,20885.492958,7.985915,2004.070423
549,경기도 화성시 향남읍 하길리,0.000000,82.255331,202091.812500,15.562500,38665.625000,13.187500,2015.000000
550,경기도 화성시 향남읍 행정리,0.000000,84.923159,202039.215962,15.765258,31768.356808,8.215962,2008.253521

In [43]:
boondang = df_group['시군구'].str.contains("분당동|수내동|정자동|서현동|이매동|야탑동|분당구 금곡동|구미동")

boondang_df = df_group[boondang]

boondang_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
152,경기도 성남분당구 구미동,0.000000,81.620000,202030.184397,14.687943,99398.581560,8.964539,1995.113475
153,경기도 성남분당구 금곡동,0.000000,83.550361,202029.409836,16.540984,109881.967213,9.245902,1996.032787
156,경기도 성남분당구 분당동,0.000000,81.864375,202034.020833,16.135417,100821.875000,8.343750,1992.562500
158,경기도 성남분당구 서현동,0.000000,82.041302,202036.734375,15.604167,116059.635417,9.697917,1991.901042
159,경기도 성남분당구 수내동,0.000000,84.723030,202033.424242,15.969697,131198.989899,8.909091,1992.343434
160,경기도 성남분당구 야탑동,0.000000,80.995075,202031.761905,14.394558,92962.585034,7.802721,1994.346939
162,경기도 성남분당구 이매동,0.000000,82.521651,202030.137615,15.788991,118263.761468,7.642202,1992.724771
163,경기도 성남분당구 정자동,0.151079,83.449436,202039.841727,15.208633,121512.230216,11.064748,1996.978417
205,경기도 수원장안구 정자동,3.688679,83.270777,202059.268868,16.405660,50339.858491,11.075472,2001.450472

In [39]:
pyeongchon = df_group['시군구'].str.contains("비산동|관양동|호계동|평촌동")

pyeongchon_df = df_group[pyeongchon]

pyeongchon_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
282,경기도 안양동안구 관양동,2.663866,83.677164,202036.768908,16.626050,89699.579832,10.386555,2003.815126
283,경기도 안양동안구 비산동,1.200820,83.675686,202052.448770,16.436475,65956.659836,11.489754,2000.557377
284,경기도 안양동안구 평촌동,2.495690,84.331202,202037.948276,15.993534,81292.241379,10.767241,1997.012931
285,경기도 안양동안구 호계동,3.657581,83.493951,202048.862010,15.674617,60772.742760,10.362862,2001.035775

In [40]:
joongdong = df_group['시군구'].str.contains("부천시 상동|부천시 중동|대산동")

joongdong_df = df_group[joongdong]

joongdong_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
136,경기도 부천시 상동,2.288967,83.932578,202052.106830,15.642732,59093.169877,10.809107,2000.760070
150,경기도 부천시 중동,4.701550,82.452271,202045.563953,15.467054,57562.267442,10.125969,1998.781008

송산동 = 덕이동 가좌동

In [50]:
ilsan = df_group['시군구'].str.contains("식사동|동구 중산동|정발산동|동구 풍동|탄현동|대화동|덕이동|가좌동|서구 송산동|백석동|마두동|주엽동|일산동|장항동")

ilsan_df = df_group[ilsan]

ilsan_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
19,경기도 고양일산동구 마두동,0.000000,82.590597,202030.920354,14.389381,55660.398230,8.690265,1993.115044
20,경기도 고양일산동구 백석동,0.000000,81.819906,202030.259434,15.542453,56119.764151,13.240566,1999.245283
21,경기도 고양일산동구 사리현동,0.000000,83.261333,202063.477778,16.200000,24950.277778,7.633333,2004.333333
22,경기도 고양일산동구 성석동,0.000000,79.860000,202083.800000,8.800000,22640.000000,9.400000,2004.000000
23,경기도 고양일산동구 식사동,0.000000,84.555075,202024.573770,16.934426,46055.737705,11.573770,2005.967213
24,경기도 고양일산동구 장항동,0.000000,77.651129,202033.500000,14.827273,62591.363636,11.609091,1998.136364
25,경기도 고양일산동구 중산동,0.604396,82.640177,202033.266484,15.142857,41854.532967,10.304945,2004.129121
26,경기도 고양일산동구 풍동,4.364407,82.427840,202031.723164,15.336158,36827.087571,10.070621,2003.497175
27,경기도 고양일산서구 가좌동,0.000000,83.636722,202040.789700,15.922747,31274.978541,9.772532,2004.626609
28,경기도 고양일산서구 대화동,0.000000,83.863867,202032.322816,16.189320,42608.004854,10.184466,2001.111650
29,경기도 고양일산서구 덕이동,0.148936,83.673751,202039.212766,16.845745,34475.914894,9.962766,2005.329787
30,경기도 고양일산서구 일산동,1.651867,82.539594,202039.030272,16.322906,39576.731584,9.710394,1999.880928
31,경기도 고양일산서구 주엽동,0.000000,78.182231,202029.720280,15.386946,45945.850816,9.351981,1993.836830
32,경기도 고양일산서구 탄현동,0.000000,81.741378,202042.176471,16.465686,34676.838235,10.465686,2002.681373

In [46]:
wyre = df_group['시군구'].str.contains("학암동|창곡동")

wyre_df = df_group[wyre]

wyre_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
170,경기도 성남수정구 창곡동,0.0,82.313387,202041.054054,15.198198,136873.423423,9.540541,2016.351351
513,경기도 하남시 학암동,0.0,82.804427,202032.893130,15.160305,123868.320611,11.244275,2016.000000

In [47]:
pankyo = df_group['시군구'].str.contains("운중동|삼평동|판교동|백현동")

pankyo_df = df_group[pankyo]

pankyo_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
155,경기도 성남분당구 백현동,0.0,82.585319,202033.595745,15.234043,166070.212766,9.723404,2009.000000
157,경기도 성남분당구 삼평동,0.0,82.816019,202033.250000,16.093750,141333.203125,8.429688,2009.000000
161,경기도 성남분당구 운중동,0.0,84.370523,202039.386364,16.113636,131268.181818,15.159091,2009.431818
164,경기도 성남분당구 판교동,0.0,82.066656,202031.970874,17.330097,125774.669903,11.106796,2009.000000

In [49]:
gangkyo = df_group['시군구'].str.contains("이의동|영통구 하동|원천동|상현동")

gangkyo_df = df_group[gangkyo]

gangkyo_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
197,경기도 수원영통구 원천동,0.360465,84.514801,202050.279070,17.453488,101737.209302,15.139535,2010.581395
198,경기도 수원영통구 이의동,0.000000,84.089579,202050.902174,16.431159,113225.405797,11.119565,2012.094203
199,경기도 수원영통구 하동,0.000000,82.728924,202072.122340,15.617021,96055.851064,14.489362,2012.590426
365,경기도 용인수지구 상현동,0.425626,84.248895,202039.823270,15.621502,72318.466863,10.699558,2004.701031

In [63]:
dongtan = df_group['시군구'].str.contains("화성시 오산동|방교동|권선구 금곡동|반송동|석우동|기흥구 능동|영천동|기흥구 중동|화성시 청계동|영통구 신동|산척동|화성시 목동|화성시 장지동")

dongtan_df = df_group[dongtan]

dongtan_df

,시군구,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
184,경기도 수원권선구 금곡동,0.642975,84.119010,202066.885950,16.411570,50465.123967,10.538843,2007.566942
195,경기도 수원영통구 신동,0.000000,84.940211,202046.505263,17.421053,72431.052632,14.463158,2013.000000
360,경기도 용인기흥구 중동,0.015453,83.782550,202051.525386,15.348786,48553.532009,10.375276,2008.397351
521,경기도 화성시 목동,3.713592,80.752009,202057.572816,16.000000,63980.097087,11.691748,2018.002427
522,경기도 화성시 반송동,0.000000,83.139459,202040.974395,16.008535,59194.779516,12.963016,2007.233286
532,경기도 화성시 산척동,0.000000,82.439483,202075.171548,17.025105,73196.401674,11.485356,2018.280335
534,경기도 화성시 석우동,0.000000,77.152168,202040.616667,16.050000,55535.000000,14.400000,2008.000000
540,경기도 화성시 영천동,101.916370,81.785527,202050.074733,16.330961,67432.188612,11.670819,2015.629893
541,경기도 화성시 오산동,0.000000,82.026597,202055.827586,16.482759,72352.324713,11.307471,2015.405172
543,경기도 화성시 장지동,0.000000,80.671244,202059.910345,16.289655,68126.551724,10.496552,2018.427586
546,경기도 화성시 청계동,0.000000,83.418477,202042.537112,16.430499,83308.272605,12.770580,2015.317139